=== tingsu/DroidDefects/Bites-caldwell.ben.bites-1.3/bites-android/recipe.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns="http://bites-android.googlecode.com"
targetNamespace="http://bites-android.googlecode.com"
elementFormDefault="qualified">
<!-- definition of complex elements -->
  <xs:complexType name="ingredientType">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="quantity" type="xs:integer"/>
      <xs:element name="unit" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="methodType">
    <xs:sequence>
      <xs:element name="step" type="xs:string"/>
      <xs:element name="instruction" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="recipeType">
    <xs:sequence>
      <xs:element name="ingredient" type="ingredientType" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element name="method" type="methodType" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>
<!-- The Schema -->
<xs:element name="recipe" type="recipeType"/>
</xs:schema>

=== tingsu/DroidDefects/cases/Bites-caldwell.ben.bites-1.3/bites-android/RecipeExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<recipe name="curry"
xmlns="http://bites-android.googlecode.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://bites-android.googlecode.com http://bites-android.googlecode.com/svn/trunk/recipe.xsd">
  <ingredient>
    <name>fish</name>
    <quantity>2</quantity>
    <unit>fillets</unit>
  </ingredient>
  <ingredient>
    <name>lime</name>
    <quantity>1</quantity>
    <unit>lime</unit>
  </ingredient>
  <method>
    <step>1</step>
    <instruction>fry fish</instruction>
  </method>
  <method>
    <step>2</step>
    <instruction>add lime</instruction>
  </method>
</recipe>
